from .base import BaseRepository
from .category_repo import CategoryRepository
from .category_settings_repo import CategorySettingsRepository
from .city import CityRepository
from .country_repo import CountryRepository
from .material_repo import MaterialRepository
from .order_search_repo import OrderSearchRepository
from .supply import SupplyRepository
from .template_repo import TemplateRepository
from .user import UserRepository
from .wb_assembly_task import WbAssemblyTaskRepository
from .wb_order import WbOrderRepository
