"""add status column tabble supplies

Revision ID: d35c6909a3dd
Revises: 951a260d64d3
Create Date: 2025-10-02 15:46:35.739270

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d35c6909a3dd"
down_revision: Union[str, Sequence[str], None] = "951a260d64d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("supplies", sa.Column("status", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("supplies", "status")
