"""add category_settings table

Revision ID: 81937a940dbf
Revises: f8a5bc2cb7a7
Create Date: 2025-10-05 00:24:30.079003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81937a940dbf"
down_revision: Union[str, Sequence[str], None] = "f8a5bc2cb7a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_settings",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("save_as_format", sa.String(), nullable=False),
        sa.Column("output_path", sa.String(), nullable=False),
        sa.Column("save_original_data", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("category_id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("category_settings")
