"""add description column the templates table

Revision ID: 5183115df39c
Revises: 83bf1984b9c0
Create Date: 2025-10-14 23:13:29.513555

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5183115df39c"
down_revision: Union[str, Sequence[str], None] = "83bf1984b9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("description", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("templates", "description")
